"""Timestamped, no-look-ahead portfolio accounting for relative-value signals."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from .config import BacktestConfig
from .strategy import dollar_neutral_notionals, validate_signal


@dataclass(frozen=True)
class BacktestResult:
    """Portfolio path and trade ledger generated by the baseline backtest."""

    daily: pd.DataFrame
    trades: pd.DataFrame


def _one_way_cost_rate(config: BacktestConfig) -> float:
    return (
        config.etf_one_way_cost_bps
        + config.futures_one_way_cost_bps
        + config.etf_half_spread_bps
        + config.futures_half_spread_bps
    ) / 10_000


def run_backtest(prices: pd.DataFrame, signal: pd.DataFrame, config: BacktestConfig) -> BacktestResult:
    """Backtest using the previous timestamp's target for the next interval.

    At date *t*, P&L is first marked on the position established before *t*.
    The target calculated at *t-1* is then filled and charged at *t*. This one
    full-bar delay prevents the closing prices in a signal from influencing that
    same close-to-close return. Both legs receive conservative one-way costs.
    """
    validate_signal(signal)
    data = prices[["etf_close", "futures_close"]].join(signal[["etf_weight", "futures_weight"]], how="inner").copy()
    if len(data) < 2:
        raise ValueError("At least two aligned observations are required.")
    if not data.index.is_monotonic_increasing:
        raise ValueError("Prices must be ordered chronologically.")

    returns = data[["etf_close", "futures_close"]].pct_change().fillna(0.0)
    equity = config.initial_capital
    active_direction = 0.0
    ledger: list[dict[str, float | pd.Timestamp]] = []
    trade_rows: list[dict[str, float | pd.Timestamp]] = []
    one_way_cost = _one_way_cost_rate(config)

    for row_number, (timestamp, row) in enumerate(data.iterrows()):
        etf_notional, futures_notional = dollar_neutral_notionals(equity, active_direction, config.gross_exposure)
        etf_pnl = etf_notional * float(returns.at[timestamp, "etf_close"])
        futures_pnl = futures_notional * float(returns.at[timestamp, "futures_close"])
        # Financing applies only while a pair is held, and is intentionally simple.
        financing = abs(etf_notional) * config.annual_financing_rate / config.trading_days if active_direction else 0.0
        pre_trade_equity = equity + etf_pnl + futures_pnl - financing

        desired = 0.0 if row_number == 0 else float(data["etf_weight"].iloc[row_number - 1])
        if abs(desired) > config.max_gross_exposure:
            desired = float(np.sign(desired) * config.max_gross_exposure)
        turnover = abs(desired - active_direction)
        cost = pre_trade_equity * config.gross_exposure * turnover * one_way_cost
        equity = pre_trade_equity - cost
        if turnover > 0:
            trade_rows.append(
                {
                    "timestamp": timestamp,
                    "previous_direction": active_direction,
                    "new_direction": desired,
                    "turnover": turnover,
                    "cost": cost,
                }
            )

        ledger.append(
            {
                "timestamp": timestamp,
                "equity": equity,
                "daily_pnl": etf_pnl + futures_pnl - financing - cost,
                "daily_return": (equity / ledger[-1]["equity"] - 1.0) if ledger else (equity / config.initial_capital - 1.0),
                "etf_notional": etf_notional,
                "futures_notional": futures_notional,
                "position": active_direction,
                "executed_target": desired,
                "turnover": turnover,
                "transaction_cost": cost,
                "financing_cost": financing,
            }
        )
        active_direction = desired

    daily = pd.DataFrame(ledger).set_index("timestamp")
    trades = pd.DataFrame(trade_rows, columns=["timestamp", "previous_direction", "new_direction", "turnover", "cost"])
    return BacktestResult(daily=daily, trades=trades)
